server:
  port: 8890

spring:
  cloud:
    gateway:
      routes:
        - id: usuario
          uri: http://localhost:8891
          predicates:
            - Path=/usuario/**
        - id: meme
          uri: http://localhost:8892
          predicates:
            - Path=/meme/**
        - id: categoria
          uri: http://localhost:8893
          predicates:
            - Path=/categoria/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  sleuth:
    sampler:
      probability: 1.0
    zipkin:
      base-url: http://localhost:9411
      sender:
        type: web

eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    initialInstanceInfoReplicationIntervalSeconds: 30
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: loggers

logging.level:
  org.springframework.retry: trace
  org.springframework.cloud.gateway: trace
  com.netflix.discovery: trace