server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 3000

spring:
  sleuth:
    sampler:
      probability: 1.0
    zipkin:
      base-url: http://localhost:9411
      sender:
        type: web

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: loggers

logging.level:
  org.springframework.retry: trace
  com.netflix.discovery: trace